
meta_name: "Ethno | Observer, Questionner, Analyser"
meta_title: "Ethno | Observer, Questionner, Analyser"
meta_description: "Ethno anime des ateliers de sciences sociales et accompagne le public à développer un esprit critique"
meta_image: "citycolor.png" # should exist in `app/assets/images/`
